// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatSessionsByUserID = `-- name: GetChatSessionsByUserID :many
SELECT id, user_id, title, created_at FROM chat_sessions WHERE user_id = $1
`

func (q *Queries) GetChatSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, getChatSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
