// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatMessagesBySessionID = `-- name: GetChatMessagesBySessionID :many
SELECT id, session_id, role, content, created_at FROM chat_messages WHERE session_id = $1
`

func (q *Queries) GetChatMessagesBySessionID(ctx context.Context, sessionID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
