// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCollectionsByUserID = `-- name: GetCollectionsByUserID :many
SELECT id, user_id, name, created_at FROM collections WHERE user_id = $1
`

func (q *Queries) GetCollectionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollectionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
