// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fallback_images.sql

package db

import (
	"context"
)

const createFallbackImage = `-- name: CreateFallbackImage :one
INSERT INTO fallback_images (imgurl)
VALUES ($1)
RETURNING id, imgurl
`

func (q *Queries) CreateFallbackImage(ctx context.Context, imgurl string) (FallbackImage, error) {
	row := q.db.QueryRow(ctx, createFallbackImage, imgurl)
	var i FallbackImage
	err := row.Scan(&i.ID, &i.Imgurl)
	return i, err
}

const deleteFallbackImage = `-- name: DeleteFallbackImage :exec
DELETE FROM fallback_images WHERE id = $1
`

func (q *Queries) DeleteFallbackImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFallbackImage, id)
	return err
}

const getFallbackImageByID = `-- name: GetFallbackImageByID :one
SELECT id, imgurl FROM fallback_images WHERE id = $1
`

func (q *Queries) GetFallbackImageByID(ctx context.Context, id int32) (FallbackImage, error) {
	row := q.db.QueryRow(ctx, getFallbackImageByID, id)
	var i FallbackImage
	err := row.Scan(&i.ID, &i.Imgurl)
	return i, err
}

const getRandomFallbackImage = `-- name: GetRandomFallbackImage :one
SELECT id, imgurl FROM fallback_images ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomFallbackImage(ctx context.Context) (FallbackImage, error) {
	row := q.db.QueryRow(ctx, getRandomFallbackImage)
	var i FallbackImage
	err := row.Scan(&i.ID, &i.Imgurl)
	return i, err
}

const listFallbackImages = `-- name: ListFallbackImages :many
SELECT id, imgurl FROM fallback_images ORDER BY id
`

func (q *Queries) ListFallbackImages(ctx context.Context) ([]FallbackImage, error) {
	rows, err := q.db.Query(ctx, listFallbackImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackImage
	for rows.Next() {
		var i FallbackImage
		if err := rows.Scan(&i.ID, &i.Imgurl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
