// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (name, user_id)
VALUES ($1, $2)
RETURNING id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at
`

type CreateFolderParams struct {
	Name   string
	UserID int32
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.Name, arg.UserID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretKey,
		&i.UserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletedFoldersByUserID = `-- name: GetDeletedFoldersByUserID :many
SELECT id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at FROM folders
WHERE user_id = $1 AND is_deleted = TRUE
ORDER BY deleted_at DESC
`

func (q *Queries) GetDeletedFoldersByUserID(ctx context.Context, userID int32) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getDeletedFoldersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SecretKey,
			&i.UserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at FROM folders WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetFolderByID(ctx context.Context, id int32) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretKey,
		&i.UserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderBySecretKey = `-- name: GetFolderBySecretKey :one
SELECT id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at FROM folders WHERE secret_key = $1 AND is_deleted = FALSE
`

func (q *Queries) GetFolderBySecretKey(ctx context.Context, secretKey pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderBySecretKey, secretKey)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretKey,
		&i.UserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoldersByUserID = `-- name: GetFoldersByUserID :many
SELECT id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at FROM folders
WHERE user_id = $1 AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetFoldersByUserID(ctx context.Context, userID int32) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SecretKey,
			&i.UserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteFolder = `-- name: HardDeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) HardDeleteFolder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, hardDeleteFolder, id)
	return err
}

const restoreFolder = `-- name: RestoreFolder :exec
UPDATE folders
SET is_deleted = FALSE, deleted_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreFolder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, restoreFolder, id)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders
SET is_deleted = TRUE, deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteFolder, id)
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name = $2, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, name, secret_key, user_id, is_deleted, deleted_at, created_at, updated_at
`

type UpdateFolderParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretKey,
		&i.UserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
