// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linkforms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLinkform = `-- name: CreateLinkform :one
INSERT INTO linkforms (title, description, links, body, imgurl, tobefind, user_id, folder_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at
`

type CreateLinkformParams struct {
	Title       string
	Description string
	Links       string
	Body        pgtype.Text
	Imgurl      pgtype.Text
	Tobefind    bool
	UserID      int32
	FolderID    pgtype.Int4
}

func (q *Queries) CreateLinkform(ctx context.Context, arg CreateLinkformParams) (Linkform, error) {
	row := q.db.QueryRow(ctx, createLinkform,
		arg.Title,
		arg.Description,
		arg.Links,
		arg.Body,
		arg.Imgurl,
		arg.Tobefind,
		arg.UserID,
		arg.FolderID,
	)
	var i Linkform
	err := row.Scan(
		&i.SecretID,
		&i.Title,
		&i.Description,
		&i.Links,
		&i.Body,
		&i.Imgurl,
		&i.Tobefind,
		&i.UserID,
		&i.FolderID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeletedLinkformsByUserID = `-- name: GetDeletedLinkformsByUserID :many
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms
WHERE user_id = $1 AND is_deleted = TRUE
ORDER BY deleted_at DESC
`

func (q *Queries) GetDeletedLinkformsByUserID(ctx context.Context, userID int32) ([]Linkform, error) {
	rows, err := q.db.Query(ctx, getDeletedLinkformsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Linkform
	for rows.Next() {
		var i Linkform
		if err := rows.Scan(
			&i.SecretID,
			&i.Title,
			&i.Description,
			&i.Links,
			&i.Body,
			&i.Imgurl,
			&i.Tobefind,
			&i.UserID,
			&i.FolderID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkformBySecretID = `-- name: GetLinkformBySecretID :one
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms WHERE secret_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetLinkformBySecretID(ctx context.Context, secretID pgtype.UUID) (Linkform, error) {
	row := q.db.QueryRow(ctx, getLinkformBySecretID, secretID)
	var i Linkform
	err := row.Scan(
		&i.SecretID,
		&i.Title,
		&i.Description,
		&i.Links,
		&i.Body,
		&i.Imgurl,
		&i.Tobefind,
		&i.UserID,
		&i.FolderID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkformsByFolderID = `-- name: GetLinkformsByFolderID :many
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms
WHERE folder_id = $1 AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetLinkformsByFolderID(ctx context.Context, folderID pgtype.Int4) ([]Linkform, error) {
	rows, err := q.db.Query(ctx, getLinkformsByFolderID, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Linkform
	for rows.Next() {
		var i Linkform
		if err := rows.Scan(
			&i.SecretID,
			&i.Title,
			&i.Description,
			&i.Links,
			&i.Body,
			&i.Imgurl,
			&i.Tobefind,
			&i.UserID,
			&i.FolderID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkformsByUserID = `-- name: GetLinkformsByUserID :many
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms
WHERE user_id = $1 AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetLinkformsByUserID(ctx context.Context, userID int32) ([]Linkform, error) {
	rows, err := q.db.Query(ctx, getLinkformsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Linkform
	for rows.Next() {
		var i Linkform
		if err := rows.Scan(
			&i.SecretID,
			&i.Title,
			&i.Description,
			&i.Links,
			&i.Body,
			&i.Imgurl,
			&i.Tobefind,
			&i.UserID,
			&i.FolderID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicLinkforms = `-- name: GetPublicLinkforms :many
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms
WHERE tobefind = TRUE AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetPublicLinkformsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPublicLinkforms(ctx context.Context, arg GetPublicLinkformsParams) ([]Linkform, error) {
	rows, err := q.db.Query(ctx, getPublicLinkforms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Linkform
	for rows.Next() {
		var i Linkform
		if err := rows.Scan(
			&i.SecretID,
			&i.Title,
			&i.Description,
			&i.Links,
			&i.Body,
			&i.Imgurl,
			&i.Tobefind,
			&i.UserID,
			&i.FolderID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteLinkform = `-- name: HardDeleteLinkform :exec
DELETE FROM linkforms WHERE secret_id = $1
`

func (q *Queries) HardDeleteLinkform(ctx context.Context, secretID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteLinkform, secretID)
	return err
}

const restoreLinkform = `-- name: RestoreLinkform :exec
UPDATE linkforms
SET is_deleted = FALSE, deleted_at = NULL
WHERE secret_id = $1
`

func (q *Queries) RestoreLinkform(ctx context.Context, secretID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreLinkform, secretID)
	return err
}

const searchLinkforms = `-- name: SearchLinkforms :many
SELECT secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at FROM linkforms
WHERE user_id = $1 
  AND is_deleted = FALSE
  AND (title ILIKE '%' || $2 || '%' OR description ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
`

type SearchLinkformsParams struct {
	UserID  int32
	Column2 pgtype.Text
}

func (q *Queries) SearchLinkforms(ctx context.Context, arg SearchLinkformsParams) ([]Linkform, error) {
	rows, err := q.db.Query(ctx, searchLinkforms, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Linkform
	for rows.Next() {
		var i Linkform
		if err := rows.Scan(
			&i.SecretID,
			&i.Title,
			&i.Description,
			&i.Links,
			&i.Body,
			&i.Imgurl,
			&i.Tobefind,
			&i.UserID,
			&i.FolderID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLinkform = `-- name: SoftDeleteLinkform :exec
UPDATE linkforms
SET is_deleted = TRUE, deleted_at = NOW()
WHERE secret_id = $1
`

func (q *Queries) SoftDeleteLinkform(ctx context.Context, secretID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteLinkform, secretID)
	return err
}

const updateLinkform = `-- name: UpdateLinkform :one
UPDATE linkforms
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    links = COALESCE($4, links),
    body = COALESCE($5, body),
    imgurl = COALESCE($6, imgurl),
    tobefind = COALESCE($7, tobefind),
    folder_id = $8
WHERE secret_id = $1 AND is_deleted = FALSE
RETURNING secret_id, title, description, links, body, imgurl, tobefind, user_id, folder_id, is_deleted, deleted_at, created_at
`

type UpdateLinkformParams struct {
	SecretID    pgtype.UUID
	Title       string
	Description string
	Links       string
	Body        pgtype.Text
	Imgurl      pgtype.Text
	Tobefind    bool
	FolderID    pgtype.Int4
}

func (q *Queries) UpdateLinkform(ctx context.Context, arg UpdateLinkformParams) (Linkform, error) {
	row := q.db.QueryRow(ctx, updateLinkform,
		arg.SecretID,
		arg.Title,
		arg.Description,
		arg.Links,
		arg.Body,
		arg.Imgurl,
		arg.Tobefind,
		arg.FolderID,
	)
	var i Linkform
	err := row.Scan(
		&i.SecretID,
		&i.Title,
		&i.Description,
		&i.Links,
		&i.Body,
		&i.Imgurl,
		&i.Tobefind,
		&i.UserID,
		&i.FolderID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
