// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FallbackImage struct {
	ID     int32
	Imgurl string
}

type Folder struct {
	ID        int32
	Name      string
	SecretKey pgtype.UUID
	UserID    int32
	IsDeleted bool
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ForgotPassword struct {
	ID      pgtype.UUID
	Email   string
	Token   string
	Expires pgtype.Timestamptz
}

type Linkform struct {
	SecretID    pgtype.UUID
	Title       string
	Description string
	Links       string
	Body        pgtype.Text
	Imgurl      pgtype.Text
	Tobefind    bool
	UserID      int32
	FolderID    pgtype.Int4
	IsDeleted   bool
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID        int32
	Email     string
	Username  pgtype.Text
	Image     pgtype.Text
	Password  string
	Secretkey pgtype.UUID
	Verified  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Verification struct {
	ID      pgtype.UUID
	Email   string
	Token   string
	Expires pgtype.Timestamptz
}
