// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, user_id, expires_at, user_agent, ip_address
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, expires_at, created_at, last_seen_at, user_agent, ip_address, is_revoked
`

type CreateSessionParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	IpAddress pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsRevoked,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, expires_at, created_at, last_seen_at, user_agent, ip_address, is_revoked FROM sessions
WHERE id = $1 AND is_revoked = false
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsRevoked,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET is_revoked = true
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET is_revoked = true
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}
