// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSourcesByUserID = `-- name: GetSourcesByUserID :many
SELECT id, user_id, collection_id, type, status, title, original_url, s3_bucket, s3_key, content_hash, created_at FROM sources WHERE user_id = $1
`

func (q *Queries) GetSourcesByUserID(ctx context.Context, userID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, getSourcesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Type,
			&i.Status,
			&i.Title,
			&i.OriginalUrl,
			&i.S3Bucket,
			&i.S3Key,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
