// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForgotPassword = `-- name: CreateForgotPassword :one
INSERT INTO forgot_passwords (email, token, expires)
VALUES ($1, $2, $3)
RETURNING id, email, token, expires
`

type CreateForgotPasswordParams struct {
	Email   string
	Token   string
	Expires pgtype.Timestamptz
}

func (q *Queries) CreateForgotPassword(ctx context.Context, arg CreateForgotPasswordParams) (ForgotPassword, error) {
	row := q.db.QueryRow(ctx, createForgotPassword, arg.Email, arg.Token, arg.Expires)
	var i ForgotPassword
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Expires,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO verifications (email, token, expires)
VALUES ($1, $2, $3)
RETURNING id, email, token, expires
`

type CreateVerificationParams struct {
	Email   string
	Token   string
	Expires pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification, arg.Email, arg.Token, arg.Expires)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Expires,
	)
	return i, err
}

const deleteExpiredForgotPasswords = `-- name: DeleteExpiredForgotPasswords :exec
DELETE FROM forgot_passwords WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredForgotPasswords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredForgotPasswords)
	return err
}

const deleteExpiredVerifications = `-- name: DeleteExpiredVerifications :exec
DELETE FROM verifications WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerifications)
	return err
}

const deleteForgotPassword = `-- name: DeleteForgotPassword :exec
DELETE FROM forgot_passwords WHERE id = $1
`

func (q *Queries) DeleteForgotPassword(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteForgotPassword, id)
	return err
}

const deleteForgotPasswordByEmail = `-- name: DeleteForgotPasswordByEmail :exec
DELETE FROM forgot_passwords WHERE email = $1
`

func (q *Queries) DeleteForgotPasswordByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteForgotPasswordByEmail, email)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verifications WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const deleteVerificationByEmail = `-- name: DeleteVerificationByEmail :exec
DELETE FROM verifications WHERE email = $1
`

func (q *Queries) DeleteVerificationByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteVerificationByEmail, email)
	return err
}

const getForgotPasswordByEmailAndToken = `-- name: GetForgotPasswordByEmailAndToken :one
SELECT id, email, token, expires FROM forgot_passwords
WHERE email = $1 AND token = $2 AND expires > NOW()
`

type GetForgotPasswordByEmailAndTokenParams struct {
	Email string
	Token string
}

func (q *Queries) GetForgotPasswordByEmailAndToken(ctx context.Context, arg GetForgotPasswordByEmailAndTokenParams) (ForgotPassword, error) {
	row := q.db.QueryRow(ctx, getForgotPasswordByEmailAndToken, arg.Email, arg.Token)
	var i ForgotPassword
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Expires,
	)
	return i, err
}

const getVerificationByEmailAndToken = `-- name: GetVerificationByEmailAndToken :one
SELECT id, email, token, expires FROM verifications
WHERE email = $1 AND token = $2 AND expires > NOW()
`

type GetVerificationByEmailAndTokenParams struct {
	Email string
	Token string
}

func (q *Queries) GetVerificationByEmailAndToken(ctx context.Context, arg GetVerificationByEmailAndTokenParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByEmailAndToken, arg.Email, arg.Token)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Expires,
	)
	return i, err
}
